name: Slither Analysis action

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: hardhat

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Slither
        uses: crytic/slither-action@v0.3.2
        id: slither
        with:
          sarif: results.sarif
          fail-on: none
          target: 'hardhat'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
